export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const SET_ELECTIONS = 'SET_ELECTIONS';
export const GET_ELECTIONS = 'GET_ELECTIONS';
